name: Chimera
description: A native UI framework
meta_description: "Chimera, a native UI framework based on the web"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /chimera/
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
